-- books table seeds here (Example)

insert into books (name, user_id, author, date_added, is_complete) values ('The Winds of Winter', 1, 'Fakie Author', '2021-01-01', false);
insert into books (name, user_id, author, date_added, is_complete) values ('Harry Potter', 1, 'J.K Rowling', '2020-10-10', false);
insert into books (user_id, name, author, date_added, is_complete) values (1, 'Customizable neutral moratorium', 'Garwood Davidovic', '4/22/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (7, 'Organic zero defect concept', 'Jaimie Ricardon', '2/23/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (6, 'Diverse cohesive help-desk', 'Celeste Grindell', '3/2/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (3, 'Synchronised analyzing adapter', 'Erma Benedtti', '10/28/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (29, 'Function-based stable strategy', 'Kermie Greave', '12/6/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (26, 'Secured optimal middleware', 'Lynnette Ellgood', '6/22/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (19, 'Right-sized multimedia functionalities', 'Skipton Fosten', '1/6/2021', false);
insert into books (user_id, name, author, date_added, is_complete) values (18, 'Quality-focused homogeneous analyzer', 'Mirabella Yitzhakof', '5/9/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (3, 'Universal client-driven alliance', 'Chanda Colbourn', '3/11/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (17, 'Open-source clear-thinking info-mediaries', 'Lemar Marval', '8/15/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (12, 'Assimilated well-modulated flexibility', 'Ronny Skermer', '10/12/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (25, 'Robust explicit artificial intelligence', 'Wheeler Pakeman', '6/2/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (8, 'Face to face disintermediate monitoring', 'Oralia Zanolli', '3/21/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (12, 'Persistent global portal', 'Brendin Jouanet', '5/21/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (16, 'Cloned asynchronous infrastructure', 'Mac Litterick', '10/26/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (21, 'Extended bifurcated info-mediaries', 'Meriel Hardan', '4/18/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (5, 'Integrated modular throughput', 'Montgomery Ashmore', '3/25/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (5, 'User-friendly local open architecture', 'Maire Herety', '7/3/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (15, 'Versatile global knowledge base', 'Murray Haglinton', '3/14/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (23, 'Implemented needs-based structure', 'Addie LaBastida', '7/19/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (16, 'Assimilated multi-state access', 'Louisa Lyddiard', '5/4/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (19, 'Streamlined solution-oriented moderator', 'Angelina Dowman', '6/1/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (4, 'Reduced asynchronous software', 'Bendicty McGibbon', '11/12/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (21, 'Self-enabling bottom-line help-desk', 'Ally Guppy', '6/20/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (30, 'Seamless multimedia utilisation', 'Noby Hullock', '4/27/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (16, 'Switchable multi-tasking collaboration', 'Goober Redgewell', '3/10/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (13, 'Self-enabling multi-tasking hierarchy', 'Issy Gorey', '9/15/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (23, 'Re-engineered multi-state circuit', 'Kermit Bindin', '8/29/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (26, 'Organic radical encoding', 'Isa Traher', '2/17/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (21, 'Mandatory heuristic approach', 'Rozanne Avrahamian', '1/28/2021', true);
insert into books (user_id, name, author, date_added, is_complete) values (5, 'Front-line interactive conglomeration', 'Emmerich Gayden', '9/13/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (1, 'Open-architected content-based secured line', 'Devland Santacrole', '3/18/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (13, 'Innovative discrete extranet', 'Jackelyn Bourke', '7/1/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (23, 'Distributed analyzing alliance', 'Coral Lawee', '4/3/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (1, 'Enterprise-wide homogeneous focus group', 'Valeda Damsell', '10/1/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (6, 'Down-sized optimal monitoring', 'Addie Farlow', '1/3/2021', false);
insert into books (user_id, name, author, date_added, is_complete) values (22, 'User-friendly neutral instruction set', 'Cristiano Maber', '6/17/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (1, 'Polarised intangible database', 'Cornela Rydzynski', '7/16/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (13, 'Operative web-enabled website', 'Karney de Zamora', '9/21/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (13, 'Realigned modular Graphical User Interface', 'Sloan Bertelet', '12/6/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (29, 'Future-proofed analyzing attitude', 'Rodrique Zambonini', '4/30/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (24, 'Triple-buffered content-based workforce', 'Olenka Worsnap', '10/12/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (4, 'User-centric actuating help-desk', 'Rupert Urlich', '2/17/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (15, 'Diverse bi-directional frame', 'Arvy Clelland', '8/18/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (8, 'Cloned bandwidth-monitored hardware', 'Karlie Steaning', '10/7/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (13, 'Monitored analyzing collaboration', 'Mycah Sapir', '2/4/2021', false);
insert into books (user_id, name, author, date_added, is_complete) values (28, 'Cross-platform secondary initiative', 'Petronia Orrock', '3/27/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (24, 'Re-contextualized tertiary ability', 'Lorette Pulver', '2/6/2021', false);
insert into books (user_id, name, author, date_added, is_complete) values (22, 'Ameliorated modular core', 'Rosina Skinley', '4/14/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (22, 'Open-architected web-enabled definition', 'Cchaddie Pentelo', '2/5/2021', false);
insert into books (user_id, name, author, date_added, is_complete) values (4, 'Re-contextualized stable structure', 'Lib Hallums', '7/27/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (24, 'Networked high-level hardware', 'Meagan Eeles', '2/24/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (27, 'Decentralized asymmetric pricing structure', 'Abel Fareweather', '3/1/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (11, 'User-friendly needs-based archive', 'Dimitri Klaggeman', '8/19/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (3, 'Networked directional system engine', 'Freddi Bridle', '7/9/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (2, 'Phased 4th generation budgetary management', 'Loralie Ruppele', '10/20/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (21, 'Synergized object-oriented info-mediaries', 'Gay Syde', '5/17/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (22, 'Visionary solution-oriented workforce', 'Lorie Ohrtmann', '7/30/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (24, 'Business-focused zero tolerance hardware', 'Natasha Hallgath', '8/23/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (15, 'Configurable national throughput', 'Casey Dufaire', '7/24/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (23, 'Face to face methodical infrastructure', 'Bobbie Hedger', '7/28/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (19, 'Streamlined cohesive frame', 'Jesus Gedney', '1/14/2021', true);
insert into books (user_id, name, author, date_added, is_complete) values (5, 'Public-key asymmetric algorithm', 'Allyce Gorringe', '6/24/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (15, 'Team-oriented 24/7 website', 'Flynn Naris', '4/14/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (23, 'Front-line fault-tolerant orchestration', 'Enrique Motherwell', '4/9/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (30, 'Enhanced context-sensitive synergy', 'Eadith Bordes', '10/3/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (6, 'Optimized 5th generation encoding', 'Mireille Flaunders', '10/20/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (13, 'Right-sized system-worthy strategy', 'Chaunce Haworth', '8/21/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (24, 'Versatile scalable orchestration', 'Laurianne Pardie', '11/20/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (7, 'Inverse secondary collaboration', 'Warden Maplesden', '4/7/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (1, 'Business-focused attitude-oriented structure', 'Melba Polamontayne', '1/19/2021', false);
insert into books (user_id, name, author, date_added, is_complete) values (5, 'Versatile mission-critical matrix', 'Margarethe Robjant', '10/28/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (3, 'Public-key global approach', 'Lani Mayer', '8/10/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (10, 'Right-sized motivating local area network', 'Ursa Younghusband', '3/13/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (21, 'Centralized encompassing standardization', 'Barbra Prettyjohn', '8/17/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (6, 'Digitized regional info-mediaries', 'Riane Larking', '9/3/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (25, 'Universal web-enabled array', 'Karlis Baress', '2/23/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (5, 'Exclusive holistic open system', 'Ingrid Carhart', '6/4/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (14, 'Devolved regional focus group', 'Torrey Blackey', '10/11/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (13, 'Intuitive attitude-oriented toolset', 'Simonne Arbuckel', '9/8/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (10, 'Optimized clear-thinking alliance', 'Andreana McClymond', '5/15/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (18, 'Sharable logistical artificial intelligence', 'Aurora Turbitt', '7/24/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (7, 'Switchable uniform leverage', 'Orazio Bisseker', '8/12/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (7, 'Proactive human-resource budgetary management', 'Rollins Soppit', '2/8/2021', true);
insert into books (user_id, name, author, date_added, is_complete) values (14, 'Decentralized fault-tolerant system engine', 'Maris Cotesford', '6/4/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (13, 'Advanced fault-tolerant monitoring', 'Camila Meni', '7/6/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (3, 'Universal well-modulated ability', 'Garik Barizeret', '5/19/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (4, 'Virtual system-worthy system engine', 'Gabby Najara', '12/6/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (7, 'Centralized full-range Graphic Interface', 'Dante Tait', '10/16/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (5, 'Balanced multi-state core', 'Oralia Soggee', '8/12/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (15, 'Universal optimizing circuit', 'Jerrylee Valiant', '4/24/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (17, 'Pre-emptive national access', 'Kerwinn Kamen', '8/6/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (2, 'Virtual transitional intranet', 'Beulah Kenen', '4/12/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (25, 'Diverse empowering functionalities', 'Kara Gosney', '3/15/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (7, 'Mandatory neutral superstructure', 'Mikael Bunclark', '9/2/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (25, 'Innovative exuding contingency', 'Ardelle Gimenez', '5/22/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (1, 'Open-source systematic focus group', 'Jerrie Lorincz', '2/13/2020', true);
insert into books (user_id, name, author, date_added, is_complete) values (26, 'Organized homogeneous matrices', 'Thelma Creegan', '8/15/2020', false);
insert into books (user_id, name, author, date_added, is_complete) values (29, 'Seamless fresh-thinking middleware', 'Georg Smellie', '1/22/2021', true);
insert into books (user_id, name, author, date_added, is_complete) values (28, 'Streamlined analyzing architecture', 'Heath Almon', '5/28/2020', false);

GRANT SELECT, UPDATE, INSERT, UPDATE on books to labber;
GRANT USAGE, SELECT ON SEQUENCE books to labber;
GRANT ALL PRIVILEGES ON TABLE books to labber;
