-- books table seeds here (Example)

INSERT INTO books (title, user_id, author, date_added, is_complete)
VALUES ('The Winds of Winter', 1, 'Fakie Author', '2021-01-01', FALSE),
('Harry Potter', 1, 'J.K Rowling', '2020-10-10', FALSE)

insert into books (title, user_id, author, date_added) values ('Automated bifurcated project', 87, 'Leyla Farnish', '9/17/2020');
insert into books (title, user_id, author, date_added) values ('Re-engineered scalable definition', 92, 'Marya Mitchall', '1/18/2021');
insert into books (title, user_id, author, date_added) values ('Virtual global monitoring', 75, 'Aluino Cattermole', '5/16/2020');
insert into books (title, user_id, author, date_added) values ('Balanced reciprocal archive', 38, 'Devin Syrad', '12/25/2020');
insert into books (title, user_id, author, date_added) values ('Stand-alone clear-thinking infrastructure', 17, 'Malorie Rapp', '1/13/2021');
insert into books (title, user_id, author, date_added) values ('Reduced bi-directional success', 36, 'Harald Swift', '5/3/2020');
insert into books (title, user_id, author, date_added) values ('Streamlined bottom-line budgetary management', 82, 'Dennis McCorkindale', '7/19/2020');
insert into books (title, user_id, author, date_added) values ('Profit-focused asymmetric info-mediaries', 90, 'Gaelan McTerrelly', '3/3/2020');
insert into books (title, user_id, author, date_added) values ('Down-sized uniform hardware', 22, 'Walt Whitebrook', '11/6/2020');
insert into books (title, user_id, author, date_added) values ('Upgradable global success', 27, 'Jory Hallybone', '9/25/2020');
insert into books (title, user_id, author, date_added) values ('Self-enabling context-sensitive matrix', 62, 'Anett Leuren', '10/28/2020');
insert into books (title, user_id, author, date_added) values ('Face to face coherent implementation', 49, 'Amalia Buttle', '12/9/2020');
insert into books (title, user_id, author, date_added) values ('Team-oriented contextually-based architecture', 95, 'Fran Brower', '1/30/2021');
insert into books (title, user_id, author, date_added) values ('Centralized 24 hour solution', 47, 'Erick Overshott', '5/25/2020');
insert into books (title, user_id, author, date_added) values ('Streamlined value-added hierarchy', 2, 'Saxon McConnell', '5/5/2020');
insert into books (title, user_id, author, date_added) values ('Phased methodical moderator', 36, 'Devinne Smeal', '8/23/2020');
insert into books (title, user_id, author, date_added) values ('Compatible transitional website', 6, 'Jamima Ruusa', '2/21/2020');
insert into books (title, user_id, author, date_added) values ('Front-line holistic methodology', 52, 'Staford Breeder', '1/4/2021');
insert into books (title, user_id, author, date_added) values ('Automated demand-driven infrastructure', 47, 'Cad Cossey', '11/7/2020');
insert into books (title, user_id, author, date_added) values ('Assimilated scalable matrices', 93, 'Giralda Isaq', '2/13/2020');
insert into books (title, user_id, author, date_added) values ('Synergized coherent complexity', 23, 'Sanson Basketfield', '6/19/2020');
insert into books (title, user_id, author, date_added) values ('Digitized methodical collaboration', 25, 'Aldon Hadeke', '4/16/2020');
insert into books (title, user_id, author, date_added) values ('Integrated zero administration projection', 61, 'Hilde Magner', '12/14/2020');
insert into books (title, user_id, author, date_added) values ('Intuitive fresh-thinking service-desk', 84, 'Kittie McKearnen', '5/31/2020');
insert into books (title, user_id, author, date_added) values ('Reduced multimedia contingency', 13, 'Bill Pawlicki', '7/1/2020');
insert into books (title, user_id, author, date_added) values ('Cross-group scalable flexibility', 29, 'Roobbie Waples', '10/25/2020');
insert into books (title, user_id, author, date_added) values ('Ergonomic optimizing application', 71, 'Cristy Crawshay', '11/24/2020');
insert into books (title, user_id, author, date_added) values ('Pre-emptive responsive leverage', 15, 'Lotta Gouch', '1/6/2021');
insert into books (title, user_id, author, date_added) values ('Decentralized secondary array', 34, 'Briny Muncie', '3/11/2020');
insert into books (title, user_id, author, date_added) values ('Persistent heuristic hierarchy', 44, 'Edward Gritsaev', '11/24/2020');
insert into books (title, user_id, author, date_added) values ('Face to face national process improvement', 39, 'Yulma Checcuzzi', '7/13/2020');
insert into books (title, user_id, author, date_added) values ('Synergized intangible concept', 76, 'Row Lumsden', '7/12/2020');
insert into books (title, user_id, author, date_added) values ('Progressive hybrid analyzer', 64, 'Valene Ambrogini', '5/16/2020');
insert into books (title, user_id, author, date_added) values ('Managed composite function', 10, 'Joela Rymell', '5/19/2020');
insert into books (title, user_id, author, date_added) values ('Synchronised optimizing neural-net', 66, 'Marlin Mellish', '8/12/2020');
insert into books (title, user_id, author, date_added) values ('Devolved discrete website', 2, 'Sibby Castelletti', '4/1/2020');
insert into books (title, user_id, author, date_added) values ('Reactive logistical pricing structure', 38, 'Jozef Goodsell', '7/23/2020');
insert into books (title, user_id, author, date_added) values ('Front-line value-added flexibility', 96, 'Woodie Dossettor', '3/15/2020');
insert into books (title, user_id, author, date_added) values ('Synergized stable solution', 31, 'Ketti Karle', '2/15/2020');
insert into books (title, user_id, author, date_added) values ('Visionary analyzing complexity', 90, 'Madelle Prime', '1/3/2021');
insert into books (title, user_id, author, date_added) values ('Expanded bifurcated framework', 47, 'Rena Crookes', '7/24/2020');
insert into books (title, user_id, author, date_added) values ('Pre-emptive solution-oriented contingency', 49, 'Shawnee Lortz', '6/22/2020');
insert into books (title, user_id, author, date_added) values ('Multi-layered actuating array', 67, 'Marita Marcussen', '9/8/2020');
insert into books (title, user_id, author, date_added) values ('Fundamental bottom-line access', 81, 'Shurlocke Sidon', '10/31/2020');
insert into books (title, user_id, author, date_added) values ('Innovative attitude-oriented hub', 38, 'Claybourne Benfield', '7/4/2020');
insert into books (title, user_id, author, date_added) values ('Advanced non-volatile open architecture', 84, 'Adora Daish', '9/21/2020');
insert into books (title, user_id, author, date_added) values ('Face to face content-based encoding', 37, 'Emylee Firmage', '10/1/2020');
insert into books (title, user_id, author, date_added) values ('Customer-focused zero administration infrastructure', 86, 'Kristin Aldwich', '3/7/2020');
insert into books (title, user_id, author, date_added) values ('Operative methodical methodology', 2, 'Wakefield Colville', '5/5/2020');
insert into books (title, user_id, author, date_added) values ('Operative scalable encoding', 20, 'Delly Marnane', '5/11/2020');
insert into books (title, user_id, author, date_added) values ('Intuitive mission-critical open architecture', 57, 'Dorie Piser', '3/18/2020');
insert into books (title, user_id, author, date_added) values ('Expanded multimedia task-force', 65, 'Kelcy Sans', '1/25/2021');
insert into books (title, user_id, author, date_added) values ('Versatile zero administration artificial intelligence', 24, 'Evvy Zecchi', '11/27/2020');
insert into books (title, user_id, author, date_added) values ('Synchronised responsive product', 2, 'Zachariah Scammonden', '3/11/2020');
insert into books (title, user_id, author, date_added) values ('Multi-tiered human-resource standardization', 55, 'Alley Marousek', '4/7/2020');
insert into books (title, user_id, author, date_added) values ('Visionary even-keeled project', 32, 'Mamie Bonnavant', '10/21/2020');
insert into books (title, user_id, author, date_added) values ('Realigned user-facing data-warehouse', 25, 'Herbert Gebby', '9/2/2020');
insert into books (title, user_id, author, date_added) values ('Innovative client-driven time-frame', 26, 'Brig Vesty', '3/8/2020');
insert into books (title, user_id, author, date_added) values ('Innovative eco-centric time-frame', 89, 'Nicol Sandal', '7/27/2020');
insert into books (title, user_id, author, date_added) values ('Visionary 6th generation instruction set', 23, 'Thain Scroxton', '12/6/2020');
insert into books (title, user_id, author, date_added) values ('Object-based human-resource data-warehouse', 57, 'Hendrika Leese', '8/25/2020');
insert into books (title, user_id, author, date_added) values ('Streamlined static knowledge user', 64, 'Nara Berkowitz', '6/26/2020');
insert into books (title, user_id, author, date_added) values ('User-friendly solution-oriented parallelism', 91, 'Halli Rulten', '7/12/2020');
insert into books (title, user_id, author, date_added) values ('Quality-focused empowering alliance', 21, 'Glenine Le Floch', '2/15/2020');
insert into books (title, user_id, author, date_added) values ('Fully-configurable optimizing matrix', 13, 'Nathaniel Frigot', '10/28/2020');
insert into books (title, user_id, author, date_added) values ('Re-engineered scalable analyzer', 45, 'Demetris Goose', '12/21/2020');
insert into books (title, user_id, author, date_added) values ('User-centric optimal parallelism', 16, 'Gothart Foskin', '5/27/2020');
insert into books (title, user_id, author, date_added) values ('Ameliorated context-sensitive capacity', 38, 'Abrahan Laxton', '8/1/2020');
insert into books (title, user_id, author, date_added) values ('Enterprise-wide multimedia pricing structure', 96, 'Perry Doak', '8/15/2020');
insert into books (title, user_id, author, date_added) values ('Sharable coherent definition', 56, 'Peadar Lethardy', '7/14/2020');
insert into books (title, user_id, author, date_added) values ('Realigned secondary customer loyalty', 92, 'Wolfy Cisland', '4/27/2020');
insert into books (title, user_id, author, date_added) values ('Face to face systematic ability', 42, 'Flory Goodlet', '4/2/2020');
insert into books (title, user_id, author, date_added) values ('Optimized optimizing ability', 21, 'Greer Ledner', '3/13/2020');
insert into books (title, user_id, author, date_added) values ('Diverse multi-state support', 30, 'Lona Spino', '9/27/2020');
insert into books (title, user_id, author, date_added) values ('Progressive radical flexibility', 48, 'Ernesto Rehme', '11/25/2020');
insert into books (title, user_id, author, date_added) values ('Horizontal intermediate local area network', 60, 'Pavlov Macken', '9/4/2020');
insert into books (title, user_id, author, date_added) values ('Function-based high-level matrix', 29, 'Gerick Litster', '2/26/2020');
insert into books (title, user_id, author, date_added) values ('Extended multi-tasking time-frame', 80, 'Ardra Elcox', '12/20/2020');
insert into books (title, user_id, author, date_added) values ('Vision-oriented impactful projection', 6, 'Wilow Postans', '12/29/2020');
insert into books (title, user_id, author, date_added) values ('Polarised clear-thinking projection', 36, 'Godfree Paschek', '7/26/2020');
insert into books (title, user_id, author, date_added) values ('Streamlined disintermediate structure', 42, 'Joceline Roache', '1/21/2021');
insert into books (title, user_id, author, date_added) values ('Expanded high-level success', 74, 'Otho Hyatt', '2/4/2021');
insert into books (title, user_id, author, date_added) values ('Secured tangible access', 30, 'Domingo Anmore', '6/6/2020');
insert into books (title, user_id, author, date_added) values ('Cloned mobile paradigm', 13, 'Mayer Petruk', '3/26/2020');
insert into books (title, user_id, author, date_added) values ('Triple-buffered neutral moderator', 37, 'Kelcie Eim', '12/9/2020');
insert into books (title, user_id, author, date_added) values ('Persevering 5th generation synergy', 52, 'Mellie Cool', '11/21/2020');
insert into books (title, user_id, author, date_added) values ('Seamless bandwidth-monitored workforce', 55, 'Tiffie Piercy', '11/24/2020');
insert into books (title, user_id, author, date_added) values ('Automated leading edge collaboration', 29, 'Darn Winridge', '6/17/2020');
insert into books (title, user_id, author, date_added) values ('Pre-emptive modular parallelism', 76, 'Somerset Aspey', '4/7/2020');
insert into books (title, user_id, author, date_added) values ('Virtual reciprocal framework', 25, 'Bethina Skitral', '12/9/2020');
insert into books (title, user_id, author, date_added) values ('Phased full-range system engine', 23, 'Gabbi Aylmore', '9/7/2020');
insert into books (title, user_id, author, date_added) values ('Re-engineered mission-critical moratorium', 20, 'Harriott Boughtwood', '3/17/2020');
insert into books (title, user_id, author, date_added) values ('Synergistic value-added task-force', 77, 'Kristyn Ahrens', '7/12/2020');
insert into books (title, user_id, author, date_added) values ('Extended maximized system engine', 19, 'Daisey Sowter', '11/18/2020');
insert into books (title, user_id, author, date_added) values ('Re-contextualized modular projection', 62, 'Stacee Lakeland', '2/14/2020');
insert into books (title, user_id, author, date_added) values ('Re-contextualized optimal architecture', 36, 'Geoffrey Growcott', '4/26/2020');
insert into books (title, user_id, author, date_added) values ('Fundamental coherent framework', 36, 'Innis Shapira', '8/9/2020');
insert into books (title, user_id, author, date_added) values ('Business-focused real-time customer loyalty', 45, 'Ulrike Colville', '7/8/2020');
insert into books (title, user_id, author, date_added) values ('Reduced incremental service-desk', 28, 'Sally Molson', '1/28/2021');
insert into books (title, user_id, author, date_added) values ('Switchable context-sensitive emulation', 3, 'Leonelle Tyce', '12/17/2020');

GRANT SELECT, UPDATE, INSERT, UPDATE on books to labber;
