
-- books
insert into items (category_id, user_id, name, date_added) values (1, 20, 'Mandatory encompassing analyzer', '5/7/2020');
insert into items (category_id, user_id, name, date_added) values (1, 21, 'Focused contextually-based hub', '8/2/2020');
insert into items (category_id, user_id, name, date_added) values (1, 29, 'Stand-alone optimal array', '2/22/2020');
insert into items (category_id, user_id, name, date_added) values (1, 10, 'Reverse-engineered neutral help-desk', '3/17/2020');
insert into items (category_id, user_id, name, date_added) values (1, 2, 'Object-based impactful migration', '10/11/2020');
insert into items (category_id, user_id, name, date_added) values (1, 30, 'Reduced modular function', '4/6/2020');
insert into items (category_id, user_id, name, date_added) values (1, 8, 'Profit-focused scalable architecture', '10/19/2020');
insert into items (category_id, user_id, name, date_added) values (1, 27, 'Business-focused encompassing moratorium', '7/6/2020');
insert into items (category_id, user_id, name, date_added) values (1, 7, 'Phased full-range customer loyalty', '1/15/2021');
insert into items (category_id, user_id, name, date_added) values (1, 16, 'Versatile reciprocal ability', '7/31/2020');
insert into items (category_id, user_id, name, date_added) values (1, 8, 'Up-sized intangible support', '7/23/2020');
insert into items (category_id, user_id, name, date_added) values (1, 20, 'Assimilated web-enabled structure', '5/7/2020');
insert into items (category_id, user_id, name, date_added) values (1, 9, 'Persevering bi-directional synergy', '11/14/2020');
insert into items (category_id, user_id, name, date_added) values (1, 2, 'Proactive needs-based benchmark', '2/2/2021');
insert into items (category_id, user_id, name, date_added) values (1, 6, 'Configurable directional array', '11/16/2020');
insert into items (category_id, user_id, name, date_added) values (1, 9, 'Exclusive didactic software', '9/5/2020');
insert into items (category_id, user_id, name, date_added) values (1, 5, 'Multi-lateral zero defect internet solution', '4/19/2020');
insert into items (category_id, user_id, name, date_added) values (1, 1, 'Cross-platform executive budgetary management', '9/17/2020');
insert into items (category_id, user_id, name, date_added) values (1, 23, 'Persistent 24 hour frame', '12/31/2020');
insert into items (category_id, user_id, name, date_added) values (1, 9, 'Optimized reciprocal pricing structure', '6/4/2020');
insert into items (category_id, user_id, name, date_added) values (1, 5, 'Cross-platform discrete frame', '5/20/2020');
insert into items (category_id, user_id, name, date_added) values (1, 24, 'Profit-focused 6th generation interface', '5/2/2020');
insert into items (category_id, user_id, name, date_added) values (1, 26, 'Function-based explicit functionalities', '4/19/2020');
insert into items (category_id, user_id, name, date_added) values (1, 22, 'Polarised tangible adapter', '9/3/2020');
insert into items (category_id, user_id, name, date_added) values (1, 1, 'Networked holistic structure', '7/15/2020');
insert into items (category_id, user_id, name, date_added) values (1, 13, 'Ameliorated 6th generation contingency', '10/29/2020');
insert into items (category_id, user_id, name, date_added) values (1, 28, 'Progressive human-resource encryption', '4/19/2020');
insert into items (category_id, user_id, name, date_added) values (1, 14, 'Secured systemic emulation', '6/15/2020');
insert into items (category_id, user_id, name, date_added) values (1, 27, 'Devolved systematic matrix', '12/13/2020');
insert into items (category_id, user_id, name, date_added) values (1, 8, 'Persistent foreground system engine', '6/16/2020');
insert into items (category_id, user_id, name, date_added) values (1, 16, 'Enhanced real-time Graphical User Interface', '3/20/2020');
insert into items (category_id, user_id, name, date_added) values (1, 7, 'Adaptive directional paradigm', '12/17/2020');
-- movies
insert into items (category_id, user_id, name, date_added) values (2, 16, 'Buddies (Colegas)', '9/1/2020');
insert into items (category_id, user_id, name, date_added) values (2, 2, 'Albatross', '11/21/2020');
insert into items (category_id, user_id, name, date_added) values (2, 10, 'Cochochi', '1/4/2021');
insert into items (category_id, user_id, name, date_added) values (2, 29, 'Action Jackson', '8/13/2020');
insert into items (category_id, user_id, name, date_added) values (2, 2, 'Visions of Europe', '11/16/2020');
insert into items (category_id, user_id, name, date_added) values (2, 28, 'The Missouri Breaks', '9/3/2020');
insert into items (category_id, user_id, name, date_added) values (2, 6, 'Armageddon (Armaguedon)', '12/24/2020');
insert into items (category_id, user_id, name, date_added) values (2, 6, 'Good Work (Beau travail)', '5/21/2020');
insert into items (category_id, user_id, name, date_added) values (2, 20, 'Capital (Le capital)', '7/16/2020');
insert into items (category_id, user_id, name, date_added) values (2, 29, 'Mighty, The', '4/21/2020');
insert into items (category_id, user_id, name, date_added) values (2, 25, 'Chad Hanna', '1/14/2021');
insert into items (category_id, user_id, name, date_added) values (2, 19, 'Ex-Girlfriends', '9/7/2020');
insert into items (category_id, user_id, name, date_added) values (2, 24, 'It Might Get Loud', '1/20/2021');
insert into items (category_id, user_id, name, date_added) values (2, 29, 'Triumph of the Nerds, The: The Rise of Accidental Empires', '9/2/2020');
insert into items (category_id, user_id, name, date_added) values (2, 5, 'Cialo', '5/9/2020');
insert into items (category_id, user_id, name, date_added) values (2, 21, 'Lust for Life', '6/30/2020');
insert into items (category_id, user_id, name, date_added) values (2, 4, 'Baby Geniuses', '7/12/2020');
insert into items (category_id, user_id, name, date_added) values (2, 30, 'Monkey''s Teeth (Dents du singe, Les)', '2/20/2020');
insert into items (category_id, user_id, name, date_added) values (2, 27, 'Second Chorus', '12/2/2020');
insert into items (category_id, user_id, name, date_added) values (2, 13, 'Madame Bovary', '2/27/2020');
insert into items (category_id, user_id, name, date_added) values (2, 25, 'King of the Jungle', '3/7/2020');
insert into items (category_id, user_id, name, date_added) values (2, 28, 'Attack on the Iron Coast', '11/15/2020');
insert into items (category_id, user_id, name, date_added) values (2, 17, 'Clockwatchers', '1/3/2021');
insert into items (category_id, user_id, name, date_added) values (2, 8, 'President''s Man: A Line in the Sand, The', '10/9/2020');
insert into items (category_id, user_id, name, date_added) values (2, 2, 'Delicate Balance, A', '9/24/2020');
insert into items (category_id, user_id, name, date_added) values (2, 27, 'Page Miss Glory', '6/13/2020');
insert into items (category_id, user_id, name, date_added) values (2, 19, 'Simple Twist of Fate, A', '1/28/2021')
--restaurants
insert into items (category_id, user_id, name, date_added) values (3, 1, 'Applebees', '9/11/2020');
insert into items (category_id, user_id, name, date_added) values (3, 2, 'Arbys', '4/21/2020');
insert into items (category_id, user_id, name, date_added) values (3, 3, 'Maenam', '2/21/2020');
insert into items (category_id, user_id, name, date_added) values (3, 4, 'Kingyo Izakaya', '4/28/2020');
insert into items (category_id, user_id, name, date_added) values (3, 5, 'Golden Paramount Seafood Restaurant','2/12/2020');
insert into items (category_id, user_id, name, date_added) values (3, 6, 'Le Cinq','1/1/2021');
insert into items (category_id, user_id, name, date_added) values (3, 7, 'Pujol', '6/29/2020');
insert into items (category_id, user_id, name, date_added) values (3, 8, 'SantoPalato','8/30/2020');
insert into items (category_id, user_id, name, date_added) values (3, 9, 'Burger King', '2/19/2020');
insert into items (category_id, user_id, name, date_added) values (3, 10, 'Wings', '8/14/2020');
insert into items (category_id, user_id, name, date_added) values (3, 21, 'Baton Rouge', '8/22/2020');
insert into items (category_id, user_id, name, date_added) values (3, 12, 'Chick-Fil-A', '12/31/2020');
insert into items (category_id, user_id, name, date_added) values (3, 13, 'Churchs Chicken', '4/20/2020');
insert into items (category_id, user_id, name, date_added) values (3, 14, 'Cora', '3/27/2020');
insert into items (category_id, user_id, name, date_added) values (3, 15, 'Dennys', '5/16/2020');
insert into items (category_id, user_id, name, date_added) values (3, 1, 'Dominos Pizza', '1/19/2021');
insert into items (category_id, user_id, name, date_added) values (3, 2, 'Costa Coffee', '2/29/2020');
insert into items (category_id, user_id, name, date_added) values (3, 3, 'Dairy Queen', '2/10/2020');
insert into items (category_id, user_id, name, date_added) values (3, 4, 'Five Guys', '3/28/2020');
insert into items (category_id, user_id, name, date_added) values (3, 5, 'Hooters', '2/9/2020');
insert into items (category_id, user_id, name, date_added) values (3, 6, 'IHOP', '11/29/2020');
insert into items (category_id, user_id, name, date_added) values (3, 7, 'Harveys', '3/17/2020');
insert into items (category_id, user_id, name, date_added) values (3, 8, 'Hard Rock Cafe', '9/5/2020');
insert into items (category_id, user_id, name, date_added) values (3, 9, 'The Keg', '11/26/2020');
insert into items (category_id, user_id, name, date_added) values (3, 10, 'Krispy Kreme', '9/24/2020');
insert into items (category_id, user_id, name, date_added) values (3, 19, 'Juan', '10/13/2020');
insert into items (category_id, user_id, name, date_added) values (3, 12, 'Little Casesars', '2/11/2020');
insert into items (category_id, user_id, name, date_added) values (3, 13, 'KFC', '10/10/2020');
insert into items (category_id, user_id, name, date_added) values (3, 14, 'Marrybrown', '7/1/2020');
insert into items (category_id, user_id, name, date_added) values (3, 15, 'Nandos', '10/3/2020');
insert into items (category_id, user_id, name, date_added) values (3, 16, 'Olive Garden', '9/25/2020');
insert into items (category_id, user_id, name, date_added) values (3, 17, 'Panda Express', '10/17/2020');
insert into items (category_id, user_id, name, date_added) values (3, 18, 'Outback Steakhouse', '4/8/2020');
insert into items (category_id, user_id, name, date_added) values (3, 19, 'Papa Johns Pizza', '7/23/2020');
insert into items (category_id, user_id, name, date_added) values (3, 20, 'Paris Baguette', '8/21/2020');
insert into items (category_id, user_id, name, date_added) values (3, 21, 'Pizza Hut', '12/7/2020');
insert into items (category_id, user_id, name, date_added) values (3, 23, 'Popeyes', '12/7/2020');
insert into items (category_id, user_id, name, date_added) values (3, 12, 'Quiznos', '11/15/2020');
insert into items (category_id, user_id, name, date_added) values (3, 5, 'Mercantes', '7/27/2020');
insert into items (category_id, user_id, name, date_added) values (3, 23, 'Pizza Express', '7/19/2020');
insert into items (category_id, user_id, name, date_added) values (3, 5, 'Pho Express', '3/16/2020');
insert into items (category_id, user_id, name, date_added) values (3, 21, 'Earls', '2/27/2020');
insert into items (category_id, user_id, name, date_added) values (3, 20, 'Tim Hortons', '5/15/2020');
insert into items (category_id, user_id, name, date_added) values (3, 29, 'Danbo', '11/27/2020');
insert into items (category_id, user_id, name, date_added) values (3, 2, 'Green Leaf', '7/11/2020');
insert into items (category_id, user_id, name, date_added) values (3, 4, 'Sushi Mori', '4/15/2020');
insert into items (category_id, user_id, name, date_added) values (3, 10, 'Subway', '1/21/2021');
insert into items (category_id, user_id, name, date_added) values (3, 23, 'Kurry Up', '3/29/2020');
insert into items (category_id, user_id, name, date_added) values (3, 12, 'Sushi California', '5/5/2020');
insert into items (category_id, user_id, name, date_added) values (3, 10, 'Stephos', '10/4/2020');
insert into items (category_id, user_id, name, date_added) values (3, 3, 'Cactus Club', '8/9/2020');
insert into items (category_id, user_id, name, date_added) values (3, 23, 'Saku', '5/11/2020');

--products
insert into items (category_id, user_id, name, date_added) values (4, 1, 'Playstation 5', '4/10/2020');
insert into items (category_id, user_id, name, date_added) values (4, 11, 'Carrot', '12/27/2020');
insert into items (category_id, user_id, name, date_added) values (4, 5, 'Fitbit Versa 2', '5/11/2020');
insert into items (category_id, user_id, name, date_added) values (4, 5, 'Apple MacBook Pro 2020', '4/7/2020');
insert into items (category_id, user_id, name, date_added) values (4, 12, 'Ikea Fado', '4/23/2020');
insert into items (category_id, user_id, name, date_added) values (4, 23, 'Stuffed Animal', '4/5/2020');
insert into items (category_id, user_id, name, date_added) values (4, 32, 'Water Bottle', '1/3/2021');
insert into items (category_id, user_id, name, date_added) values (4, 18, 'Toilet Paper', '9/22/2020');
insert into items (category_id, user_id, name, date_added) values (4, 9, 'Planner', '7/5/2020');
insert into items (category_id, user_id, name, date_added) values (4, 4, 'Mac Keyboard Polynesia', '10/9/2020');
insert into items (category_id, user_id, name, date_added) values (4, 5, 'Snowboard', '11/14/2020');
insert into items (category_id, user_id, name, date_added) values (4, 3, 'Mirror', '12/21/2020');
insert into items (category_id, user_id, name, date_added) values (4, 13, 'Nintendo', '11/23/2020');
insert into items (category_id, user_id, name, date_added) values (4, 15,'iPhone 12 Territory', '10/27/2020');
insert into items (category_id, user_id, name, date_added) values (4, 16, 'Postcards', '1/14/2021');
insert into items (category_id, user_id, name, date_added) values (4, 18,'Stamps', '2/18/2020');
insert into items (category_id, user_id, name, date_added) values (4, 21, 'Boots', '8/1/2020');
insert into items (category_id, user_id, name, date_added) values (4, 1, 'Runners', '11/30/2020');
insert into items (category_id, user_id, name, date_added) values (4, 2, 'Dog', '11/28/2020');
insert into items (category_id, user_id, name, date_added) values (4, 28,'Cat', '3/21/2020');
insert into items (category_id, user_id, name, date_added) values (4, 6,'Bike', '7/18/2020');
insert into items (category_id, user_id, name, date_added) values (4, 28, 'Skateboard', '3/7/2020');
insert into items (category_id, user_id, name, date_added) values (4, 29,'Skis', '8/12/2020');
insert into items (category_id, user_id, name, date_added) values (4, 16, 'Volleyball', '12/5/2020');
insert into items (category_id, user_id, name, date_added) values (4, 15, 'Soccer Ball', '7/1/2020');
insert into items (category_id, user_id, name, date_added) values (4, 14,'Basketball', '3/16/2020');
insert into items (category_id, user_id, name, date_added) values (4, 13,'Tennis Shoes', '5/24/2020');
insert into items (category_id, user_id, name, date_added) values (4, 12, 'Goalie gloves', '8/23/2020');
insert into items (category_id, user_id, name, date_added) values (4, 11, 'Yoga Mat', '7/6/2020');
insert into items (category_id, user_id, name, date_added) values (4, 10, 'Flannel', '12/4/2020');
insert into items (category_id, user_id, name, date_added) values (4, 9, 'Dell Monitor', '1/31/2021');
insert into items (category_id, user_id, name, date_added) values (4, 8, 'Gaming Chair', '5/5/2020');
insert into items (category_id, user_id, name, date_added) values (4, 7, 'Foam Roller', '5/2/2020');
insert into items (category_id, user_id, name, date_added) values (4, 6, 'Thick Socks', '7/31/2020');
insert into items (category_id, user_id, name, date_added) values (4, 5, 'Air Fryer', '7/29/2020');
insert into items (category_id, user_id, name, date_added) values (4, 4, 'Vacuum', '2/11/2020');
insert into items (category_id, user_id, name, date_added) values (4, 3, 'Pillows', '2/24/2020');
insert into items (category_id, user_id, name, date_added) values (4, 2, 'Medical masks', '8/19/2020');
insert into items (category_id, user_id, name, date_added) values (4, 1, 'Lipstick', '11/2/2020');
