--Movie table seeds here

insert into movies (user_id, title, date_added, is_complete) values (80, 'Beauty Day', '7/19/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (47, 'Sword of Gideon', '8/2/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (88, 'Delirious', '9/17/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (85, 'Pressure Point ', '3/15/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (87, 'Declaration of War (La Guerre est Déclarée)', '4/17/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (53, 'Exploding Girl, The', '1/10/2021', false);
insert into movies (user_id, title, date_added, is_complete) values (95, 'Charlie Chan at the Wax Museum', '9/29/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (58, 'My Fair Lady', '3/13/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (96, 'Star, The', '3/2/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (52, 'Interior. Leather Bar.', '10/30/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (32, 'Miami Rhapsody', '8/27/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (13, 'Bjarnfreðarson', '11/21/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (2, 'Dawn Rider, The', '12/12/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (99, 'C.H.U.D. II - Bud the Chud', '3/3/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (98, 'Chaos', '10/22/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (87, 'Way We Were, The', '6/6/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (67, 'By the Sea', '1/19/2021', true);
insert into movies (user_id, title, date_added, is_complete) values (12, 'Wild Strawberries (Smultronstället)', '6/25/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (5, 'Children of the Night', '9/13/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (84, 'Dry Cleaning (Nettoyage à sec)', '8/16/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (38, 'Upstream Color', '3/19/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (98, 'Roads to Koktebel (Koktebel)', '1/5/2021', true);
insert into movies (user_id, title, date_added, is_complete) values (81, 'Affairs of Anatol, The', '2/4/2021', false);
insert into movies (user_id, title, date_added, is_complete) values (81, 'Hell''s Gate 11:11', '6/25/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (72, 'Star Witness, The', '11/22/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (65, 'Burning Secret', '2/15/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (94, 'Stepfather, The', '4/29/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (45, 'Dawn of the Dead', '10/25/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (21, 'Irony of Fate, or Enjoy Your Bath! (Ironiya sudby, ili S legkim parom!)', '11/27/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (14, 'Epitaph', '6/3/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (12, 'Antares', '1/28/2021', true);
insert into movies (user_id, title, date_added, is_complete) values (45, 'Stardust', '3/18/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (25, 'Mea Maxima Culpa: Silence in the House of God', '6/2/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (65, 'Eye In The Sky (Gun chung)', '7/8/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (72, 'Cold Steel', '4/17/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (67, 'The Mysterious Island', '1/10/2021', false);
insert into movies (user_id, title, date_added, is_complete) values (75, 'Xuxa in Crystal Moon', '8/15/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (84, 'Brokeback Mountain', '6/28/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (22, 'Blue Blood', '1/23/2021', false);
insert into movies (user_id, title, date_added, is_complete) values (11, 'Institute, The', '5/26/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (97, 'Operation Dumbo Drop', '3/11/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (19, 'Life Aquatic with Steve Zissou, The', '11/29/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (34, 'Karlsson on the Roof', '2/9/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (6, 'Bedtime Story', '3/27/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (58, 'Jolson Sings Again', '1/3/2021', true);
insert into movies (user_id, title, date_added, is_complete) values (93, 'Ong-Bak: The Thai Warrior (Ong Bak)', '10/21/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (48, 'One Week', '4/1/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (70, 'Thief and the Cobbler, The (a.k.a. Arabian Knight)', '7/18/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (70, 'Arthur and the Invisibles', '3/2/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (43, '9500 Liberty', '9/30/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (95, 'Cutting Edge, The', '1/19/2021', true);
insert into movies (user_id, title, date_added, is_complete) values (30, 'Short Circuit 2', '9/27/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (59, 'Kids Are All Right, The', '4/26/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (7, 'Hollywood Ending', '2/4/2021', true);
insert into movies (user_id, title, date_added, is_complete) values (31, 'Liliom', '10/15/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (23, 'Absolute Beginners', '1/7/2021', false);
insert into movies (user_id, title, date_added, is_complete) values (76, 'Takers', '8/29/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (44, 'Orphanage, The (Orfanato, El)', '6/13/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (46, 'Zatoichi Meets the One-Armed Swordsman (Shin zatô Ichi: Yabure! Tôjin-ken) (Zatôichi 22)', '11/9/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (5, 'Spanish Earth, The', '4/21/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (73, 'Young Unknowns, The', '3/3/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (24, 'Letter from Siberia', '4/1/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (94, 'Transcendence', '3/5/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (10, 'Cat Came Back, The', '11/2/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (81, 'City Heat', '2/9/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (57, 'New Daughter, The', '1/25/2021', true);
insert into movies (user_id, title, date_added, is_complete) values (78, 'Great Locomotive Chase, The', '1/15/2021', false);
insert into movies (user_id, title, date_added, is_complete) values (4, '...And God Spoke', '1/18/2021', false);
insert into movies (user_id, title, date_added, is_complete) values (90, 'Woodsman, The', '3/4/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (71, 'Outbound (Periferic)', '2/13/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (57, 'Journey 2: The Mysterious Island', '7/31/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (35, 'Edmond', '7/3/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (34, 'Love and Other Drugs', '9/19/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (36, 'Ordinary Sinner', '6/13/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (61, 'Garage Days', '5/27/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (16, 'Dead Like Me: Life After Death', '9/10/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (100, 'Night Falls on Manhattan', '8/18/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (90, 'You Are God (Jestes Bogiem)', '6/17/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (83, 'Shameless (Maskeblomstfamilien )', '11/19/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (68, 'Flamenco (de Carlos Saura)', '3/10/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (59, 'Brooklyn Bridge', '4/16/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (27, 'New Jean-Claude, The (Le nouveau Jean-Claude)', '5/12/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (89, 'American Addict', '4/10/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (34, 'Mosquito Coast, The', '10/14/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (14, 'End of the Affair, The', '3/25/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (97, 'Pin...', '9/9/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (29, 'Man on High Heels', '10/3/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (66, 'Remarkable Power', '7/28/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (89, 'Nightcrawler', '4/27/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (72, 'Buried Alive II', '11/27/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (11, 'White Sands', '10/7/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (95, 'The Seventh Sin', '9/4/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (4, 'Santa Claus', '4/29/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (47, 'Petulia', '2/23/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (8, 'White Noise 2: The Light', '12/6/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (97, 'Driving Miss Daisy', '12/16/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (64, 'Destination Tokyo', '10/24/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (29, 'Winnie the Pooh and a Day for Eeyore', '5/15/2020', false);
insert into movies (user_id, title, date_added, is_complete) values (11, 'Assassination of Jesse James by the Coward Robert Ford, The', '5/7/2020', true);
insert into movies (user_id, title, date_added, is_complete) values (5, 'Entity, The', '6/2/2020', false);

GRANT SELECT, UPDATE, INSERT, UPDATE on movies to labber;
