--Movie table seeds here

insert into movies (user_id, name, date_added) values (26, 'King of the Ants', '7/15/2020');
insert into movies (user_id, name, date_added) values (10, 'Clint Eastwood: Out of the Shadows', '9/1/2020');
insert into movies (user_id, name, date_added) values (22, 'Taming of the Shrew, The', '7/4/2020');
insert into movies (user_id, name, date_added) values (6, 'Armed and Dangerous', '4/7/2020');
insert into movies (user_id, name, date_added) values (28, 'Batman: Mask of the Phantasm', '8/7/2020');
insert into movies (user_id, name, date_added) values (23, 'Player''s Club, The', '5/13/2020');
insert into movies (user_id, name, date_added) values (15, 'Hotline', '8/8/2020');
insert into movies (user_id, name, date_added) values (14, 'Mindwalk', '5/13/2020');
insert into movies (user_id, name, date_added) values (29, 'Chronic Town', '10/12/2020');
insert into movies (user_id, name, date_added) values (20, 'Universal Soldier', '2/1/2021');
insert into movies (user_id, name, date_added) values (15, 'Thrilla in Manila', '11/2/2020');
insert into movies (user_id, name, date_added) values (18, 'Sarafina!', '12/28/2020');
insert into movies (user_id, name, date_added) values (2, 'Primary Colors', '4/15/2020');
insert into movies (user_id, name, date_added) values (28, 'Reservoir Dogs', '3/7/2020');
insert into movies (user_id, name, date_added) values (25, 'Kleines Arschloch - Der Film', '9/27/2020');
insert into movies (user_id, name, date_added) values (15, 'Secret Life of Bees, The', '7/4/2020');
insert into movies (user_id, name, date_added) values (27, 'Guide to Recognizing Your Saints, A', '12/17/2020');
insert into movies (user_id, name, date_added) values (17, 'Dungeonmaster, The', '5/14/2020');
insert into movies (user_id, name, date_added) values (15, 'Bitch, The (La chienne)', '12/28/2020');
insert into movies (user_id, name, date_added) values (16, 'Heights', '9/16/2020');
insert into movies (user_id, name, date_added) values (27, 'Delivery, The', '9/16/2020');
insert into movies (user_id, name, date_added) values (23, 'Brigham City', '1/3/2021');
insert into movies (user_id, name, date_added) values (29, 'See No Evil', '1/16/2021');
insert into movies (user_id, name, date_added) values (15, 'Mr. Wrong', '9/7/2020');
insert into movies (user_id, name, date_added) values (12, 'Timerider: The Adventure of Lyle Swann', '6/11/2020');
insert into movies (user_id, name, date_added) values (26, 'None But the Lonely Heart', '5/17/2020');
insert into movies (user_id, name, date_added) values (12, 'Air Hawks', '12/18/2020');
insert into movies (user_id, name, date_added) values (21, 'BloodRayne: The Third Reich', '7/9/2020');
insert into movies (user_id, name, date_added) values (30, 'Django, Kill... If You Live, Shoot! (Se sei vivo spara)', '3/2/2020');
insert into movies (user_id, name, date_added) values (15, 'Lightning Bolt: The Power of Salad', '3/28/2020');
insert into movies (user_id, name, date_added) values (13, 'Andy Hardy''s Blonde Trouble', '10/3/2020');
insert into movies (user_id, name, date_added) values (9, 'Katyn', '4/23/2020');
insert into movies (user_id, name, date_added) values (13, 'Decalogue, The (Dekalog)', '12/15/2020');
insert into movies (user_id, name, date_added) values (20, 'New Kind of Love, A', '10/18/2020');
insert into movies (user_id, name, date_added) values (11, 'Theodore Rex', '10/27/2020');
insert into movies (user_id, name, date_added) values (9, 'Defenders of Riga', '8/27/2020');
insert into movies (user_id, name, date_added) values (15, 'Ilo Ilo', '12/22/2020');
insert into movies (user_id, name, date_added) values (24, 'India Song', '6/14/2020');
insert into movies (user_id, name, date_added) values (30, 'Big Man Japan (Dai-Nihonjin)', '9/3/2020');
insert into movies (user_id, name, date_added) values (3, 'Order, The', '11/8/2020');
insert into movies (user_id, name, date_added) values (4, 'The Ghosts in Our Machine', '10/30/2020');
insert into movies (user_id, name, date_added) values (24, 'OSS 117: Cairo, Nest of Spies (OSS 117: Le Caire nid d''espions)', '8/13/2020');
insert into movies (user_id, name, date_added) values (6, 'Powerpuff Girls, The', '6/9/2020');
insert into movies (user_id, name, date_added) values (26, 'Rated X', '11/26/2020');
insert into movies (user_id, name, date_added) values (3, 'Gotcha!', '3/25/2020');
insert into movies (user_id, name, date_added) values (17, 'Get Over It', '6/23/2020');
insert into movies (user_id, name, date_added) values (27, 'Bomb the System', '3/13/2020');
insert into movies (user_id, name, date_added) values (28, 'Mutant Chronicles', '10/5/2020');
insert into movies (user_id, name, date_added) values (9, 'John Garfield Story, The', '1/1/2021');
insert into movies (user_id, name, date_added) values (20, 'Juche Idea, The', '3/10/2020');
insert into movies (user_id, name, date_added) values (10, 'Abbott and Costello in Hollywood', '7/14/2020');
insert into movies (user_id, name, date_added) values (25, 'Come and See (Idi i smotri)', '5/31/2020');
insert into movies (user_id, name, date_added) values (24, 'Nightwatch (Nattevagten)', '1/29/2021');
insert into movies (user_id, name, date_added) values (23, 'Four Days of Naples, The (Le quattro giornate di Napoli)', '10/22/2020');
insert into movies (user_id, name, date_added) values (10, 'Diminished Capacity', '9/9/2020');
insert into movies (user_id, name, date_added) values (23, 'Proposition, The', '2/27/2020');
insert into movies (user_id, name, date_added) values (25, 'Lucy', '2/14/2020');
insert into movies (user_id, name, date_added) values (5, 'Life Less Ordinary, A', '8/8/2020');
insert into movies (user_id, name, date_added) values (7, 'Flame and Women (Honô to onna) ', '9/13/2020');
insert into movies (user_id, name, date_added) values (2, 'Rocky Saga: Going the Distance, The', '4/25/2020');
insert into movies (user_id, name, date_added) values (1, 'Repo Men', '6/13/2020');
insert into movies (user_id, name, date_added) values (25, 'Night of the Demons 2', '12/5/2020');
insert into movies (user_id, name, date_added) values (26, 'Romance on the High Seas', '7/21/2020');
insert into movies (user_id, name, date_added) values (6, 'Cookers', '5/15/2020');
insert into movies (user_id, name, date_added) values (22, 'Gayniggers From Outer Space', '4/6/2020');
insert into movies (user_id, name, date_added) values (24, 'Empty Nest (El nido vacío)', '5/14/2020');
insert into movies (user_id, name, date_added) values (27, 'Westfront 1918', '2/12/2020');
insert into movies (user_id, name, date_added) values (10, 'Loveless, The (Breakdown)', '3/23/2020');
insert into movies (user_id, name, date_added) values (3, 'Blood Trails ', '5/26/2020');
insert into movies (user_id, name, date_added) values (27, 'Jumping the Broom', '11/23/2020');
insert into movies (user_id, name, date_added) values (11, 'Alexander''s Ragtime Band', '1/28/2021');
insert into movies (user_id, name, date_added) values (18, 'Charleston', '1/1/2021');
insert into movies (user_id, name, date_added) values (15, 'Graveyard Shift (Stephen King''s Graveyard Shift)', '3/8/2020');
insert into movies (user_id, name, date_added) values (16, 'Frozen Fever', '7/15/2020');
insert into movies (user_id, name, date_added) values (19, 'Piranhaconda', '12/8/2020');
insert into movies (user_id, name, date_added) values (7, 'K-11', '1/24/2021');
insert into movies (user_id, name, date_added) values (24, 'After the Thin Man', '3/8/2020');
insert into movies (user_id, name, date_added) values (27, 'Wedding Date, The', '1/8/2021');
insert into movies (user_id, name, date_added) values (24, 'Dakota', '6/8/2020');
insert into movies (user_id, name, date_added) values (5, 'Mina Tannenbaum', '1/27/2021');
insert into movies (user_id, name, date_added) values (11, 'Anna Christie', '11/7/2020');
insert into movies (user_id, name, date_added) values (27, 'Midnight Chronicles', '5/6/2020');
insert into movies (user_id, name, date_added) values (10, 'Lovers of Hate', '12/30/2020');
insert into movies (user_id, name, date_added) values (10, 'All the Pretty Horses', '5/18/2020');
insert into movies (user_id, name, date_added) values (11, 'Breakfast at Tiffany''s', '11/23/2020');
insert into movies (user_id, name, date_added) values (2, 'Timeline', '8/6/2020');
insert into movies (user_id, name, date_added) values (14, 'Meatballs 4', '1/21/2021');
insert into movies (user_id, name, date_added) values (20, '7th Voyage of Sinbad, The', '8/10/2020');
insert into movies (user_id, name, date_added) values (11, 'From Time to Time', '1/25/2021');
insert into movies (user_id, name, date_added) values (23, 'Beetlejuice', '8/28/2020');
insert into movies (user_id, name, date_added) values (3, 'Werewolf of London', '7/29/2020');
insert into movies (user_id, name, date_added) values (7, 'Charleston', '1/13/2021');
insert into movies (user_id, name, date_added) values (25, 'Whistle Blower, The', '8/31/2020');
insert into movies (user_id, name, date_added) values (20, 'Babbitt', '2/8/2021');
insert into movies (user_id, name, date_added) values (5, 'Green Light', '9/19/2020');
insert into movies (user_id, name, date_added) values (15, 'Sherlock Holmes: The Woman in Green', '8/1/2020');
insert into movies (user_id, name, date_added) values (29, 'She Hate Me', '6/1/2020');
insert into movies (user_id, name, date_added) values (13, 'Confidence', '5/8/2020');
insert into movies (user_id, name, date_added) values (19, 'Waking Sleeping Beauty', '7/4/2020');
insert into movies (user_id, name, date_added) values (10, 'Mifune''s Last Song (Mifunes sidste sang)', '12/3/2020');

GRANT SELECT, UPDATE, INSERT, UPDATE on movies to labber;
