-- Product table seeds here (Example)
insert into products (user_id, name, date_added, is_complete) values (1, 'Playstation 5', '4/10/2020', false);
insert into products (user_id, name, date_added, is_complete) values (2, 'Carrot', '12/27/2020', false);
insert into products (user_id, name, date_added, is_complete) values (3, 'Fitbit Versa 2', '5/11/2020', true);
insert into products (user_id, name, date_added, is_complete) values (4, 'Apple MacBook Pro 2020', '4/7/2020', false);
insert into products (user_id, name, date_added, is_complete) values (5, 'Ikea Fado', '4/23/2020', true);
insert into products (user_id, name, date_added, is_complete) values (6, 'Stuffed Animal', '4/5/2020', true);
insert into products (user_id, name, date_added, is_complete) values (7, 'Water Bottle', '1/3/2021', true);
insert into products (user_id, name, date_added, is_complete) values (8, 'Toilet Paper', '9/22/2020', true);
insert into products (user_id, name, date_added, is_complete) values (9, 'Planner', '7/5/2020', false);
insert into products (user_id, name, date_added, is_complete) values (28, 'Mac Keyboard Polynesia', '10/9/2020', false);
insert into products (user_id, name, date_added, is_complete) values (3, 'Snowboard', '11/14/2020', false);
insert into products (user_id, name, date_added, is_complete) values (2, 'Mirror', '12/21/2020', false);
insert into products (user_id, name, date_added, is_complete) values (4, 'Nintendo', '11/23/2020', false);
insert into products (user_id, name, date_added, is_complete) values (5, 'iPhone 12 Territory', '10/27/2020', false);
insert into products (user_id, name, date_added, is_complete) values (6, 'Postcards', '1/14/2021', false);
insert into products (user_id, name, date_added, is_complete) values (7, 'Stamps', '2/18/2020', false);
insert into products (user_id, name, date_added, is_complete) values (8, 'Boots', '8/1/2020', false);
insert into products (user_id, name, date_added, is_complete) values (28, 'Runners', '11/30/2020', false);
insert into products (user_id, name, date_added, is_complete) values (9, 'Dog', '11/28/2020', false);
insert into products (user_id, name, date_added, is_complete) values (11, 'Cat', '3/21/2020', true);
insert into products (user_id, name, date_added, is_complete) values (12, 'Bike', '7/18/2020', false);
insert into products (user_id, name, date_added, is_complete) values (17, 'Skateboard', '3/7/2020', true);
insert into products (user_id, name, date_added, is_complete) values (17, 'Skis', '8/12/2020', false);
insert into products (user_id, name, date_added, is_complete) values (16, 'Volleyball', '12/5/2020', true);
insert into products (user_id, name, date_added, is_complete) values (18, 'Soccer Ball', '7/1/2020', false);
insert into products (user_id, name, date_added, is_complete) values (1, 'Basketball', '3/16/2020', false);
insert into products (user_id, name, date_added, is_complete) values (19, 'Tennis Shoes', '5/24/2020', false);
insert into products (user_id, name, date_added, is_complete) values (20, 'Goalie gloves', '8/23/2020', true);
insert into products (user_id, name, date_added, is_complete) values (21, 'Yoga Mat', '7/6/2020', true);
insert into products (user_id, name, date_added, is_complete) values (22, 'Flannel', '12/4/2020', false);
insert into products (user_id, name, date_added, is_complete) values (23, 'Dell Monitor', '1/31/2021', true);
insert into products (user_id, name, date_added, is_complete) values (24, 'Gaming Chair', '5/5/2020', false);
insert into products (user_id, name, date_added, is_complete) values (25, 'Foam Roller', '5/2/2020', true);
insert into products (user_id, name, date_added, is_complete) values (26, 'Thick Socks', '7/31/2020', false);
insert into products (user_id, name, date_added, is_complete) values (29, 'Air Fryer', '7/29/2020', false);
insert into products (user_id, name, date_added, is_complete) values (1, 'Vacuum', '2/11/2020', false);
insert into products (user_id, name, date_added, is_complete) values (25, 'Pillows', '2/24/2020', true);
insert into products (user_id, name, date_added, is_complete) values (1, 'Medical masks', '8/19/2020', false);
insert into products (user_id, name, date_added, is_complete) values (29, 'Lipstick', '11/2/2020', false);

GRANT SELECT, UPDATE, INSERT, UPDATE on products to labber;
GRANT USAGE, SELECT ON SEQUENCE products to labber;
GRANT ALL PRIVILEGES ON TABLE products to labber;
